run-dist:
		build/install/app/bin/app
		
build:
		./gradlew build
 
install:
		./gradlew clean install
 
run:
		./gradlew run
 
report:
		./gradlew jacocoTestReport
 
lint:
		./gradlew checkstyleMain checkstyleTest
 
test:
		./gradlew test
 
.PHONY: build

